from app.schemas.auth import LoginRequest, LoginResponse, UserInfo, UserProfile
from app.schemas.usuario import CrearUsuarioRequest, ActualizarUsuarioRequest, UsuarioResponse
from app.schemas.sector import CrearSectorRequest, ActualizarSectorRequest, SectorResponse
from app.schemas.punto_presion import CrearPuntoPresionRequest, ActualizarPuntoPresionRequest, PuntoPresionResponse
from app.schemas.registro_presion import CrearRegistroPresionRequest, RegistroPresionResponse, BulkRegistrosResponse
from app.schemas.reclamo import CrearReclamoRequest, ActualizarReclamoRequest, ReclamoResponse
from app.schemas.cuadrilla import CrearCuadrillaRequest, ActualizarCuadrillaRequest, CuadrillaResponse, CuadrillaDetalleResponse, PersonaCuadrilla
from app.schemas.elemento_red import CrearElementoRedRequest, ActualizarElementoRedRequest, ElementoRedResponse
from app.schemas.orden_servicio import CrearOrdenServicioRequest, ActualizarOrdenServicioRequest, FinalizarOrdenRequest, OrdenServicioResponse
