"""refactor_reclamos_historicos

Revision ID: 11f83d98a46c
Revises: ea775f1f8a37
Create Date: 2026-07-29 15:09:17.694537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision: str = '11f83d98a46c'
down_revision: Union[str, None] = 'ea775f1f8a37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reclamos_historicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_solicitud', sa.String(length=50), nullable=True),
    sa.Column('numero_suministro', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('tipo_problema', sa.String(length=120), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reclamos_historicos_id'), 'reclamos_historicos', ['id'], unique=False)
    op.execute('ALTER TABLE reclamos DROP COLUMN IF EXISTS latitud')
    op.execute('ALTER TABLE reclamos DROP COLUMN IF EXISTS longitud')
    op.execute('ALTER TABLE ordenes_servicio DROP COLUMN IF EXISTS responsable_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordenes_servicio', sa.Column('responsable_id', sa.Integer(), nullable=True))
    op.create_foreign_key('ordenes_servicio_responsable_id_fkey', 'ordenes_servicio', 'usuarios', ['responsable_id'], ['id'])
    op.add_column('reclamos', sa.Column('longitud', sa.Float(), nullable=True))
    op.add_column('reclamos', sa.Column('latitud', sa.Float(), nullable=True))
    op.drop_index(op.f('ix_reclamos_historicos_id'), table_name='reclamos_historicos')
    op.drop_table('reclamos_historicos')
    # ### end Alembic commands ###
