"""remove_sector_id_from_os

Revision ID: 3ed4adca7f22
Revises: 11f83d98a46c
Create Date: 2026-07-29 15:20:06.792063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision: str = '3ed4adca7f22'
down_revision: Union[str, None] = '11f83d98a46c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ordenes_servicio_sector_id_fkey', 'ordenes_servicio', type_='foreignkey')
    op.drop_column('ordenes_servicio', 'sector_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordenes_servicio', sa.Column('sector_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('ordenes_servicio_sector_id_fkey', 'ordenes_servicio', 'sectores', ['sector_id'], ['id'])
    # ### end Alembic commands ###
