"""Add os_secuencia table

Revision ID: 44eca831ba6f
Revises: e825fc93240e
Create Date: 2026-07-06 05:11:37.796872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


revision: str = '44eca831ba6f'
down_revision: Union[str, None] = 'e825fc93240e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('os_secuencia',
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('contador', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('fecha')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('os_secuencia')
    # ### end Alembic commands ###
