"""Change unique constraint on codigo_punto

Revision ID: 6b22e3062ec5
Revises: c875309ecc57
Create Date: 2026-07-29 22:18:04.550389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision: str = '6b22e3062ec5'
down_revision: Union[str, None] = 'c875309ecc57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('puntos_presion_codigo_punto_key', 'puntos_presion', type_='unique')
    op.create_unique_constraint('uq_codigo_origen', 'puntos_presion', ['codigo_punto', 'origen'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_codigo_origen', 'puntos_presion', type_='unique')
    op.create_unique_constraint('puntos_presion_codigo_punto_key', 'puntos_presion', ['codigo_punto'])
    # ### end Alembic commands ###
