"""remove_dispositivo_serie

Revision ID: b8a1f9fd17bc
Revises: 3ed4adca7f22
Create Date: 2026-07-29 15:28:30.248277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision: str = 'b8a1f9fd17bc'
down_revision: Union[str, None] = '3ed4adca7f22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registros_presion', 'dispositivo_serie')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registros_presion', sa.Column('dispositivo_serie', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
