"""remove_reservorio_asociado

Revision ID: c00b37726656
Revises: b8a1f9fd17bc
Create Date: 2026-07-29 15:34:37.946569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision: str = 'c00b37726656'
down_revision: Union[str, None] = 'b8a1f9fd17bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE elementos_red SET sector_id = NULL WHERE sector_id = (SELECT id FROM sectores WHERE nombre = 'Sector Test Modificado')")
    op.execute("DELETE FROM sectores WHERE nombre = 'Sector Test Modificado'")
    op.drop_column('sectores', 'reservorio_asociado')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sectores', sa.Column('reservorio_asociado', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
