"""agregar campos solicitante a reclamos

Revision ID: c76ece5b8293
Revises: 43574e3fb0d7
Create Date: 2026-07-01 17:02:27.360052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


revision: str = 'c76ece5b8293'
down_revision: Union[str, None] = '43574e3fb0d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reclamos', sa.Column('nombre_solicitante', sa.String(length=200), nullable=True))
    op.add_column('reclamos', sa.Column('telefono', sa.String(length=20), nullable=True))
    op.add_column('reclamos', sa.Column('email', sa.String(length=200), nullable=True))
    op.add_column('reclamos', sa.Column('numero_medidor', sa.String(length=50), nullable=True))
    op.add_column('reclamos', sa.Column('codigo_solicitud', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reclamos', 'codigo_solicitud')
    op.drop_column('reclamos', 'numero_medidor')
    op.drop_column('reclamos', 'email')
    op.drop_column('reclamos', 'telefono')
    op.drop_column('reclamos', 'nombre_solicitante')
    # ### end Alembic commands ###
