"""Add origen and zona to puntos and registros

Revision ID: c875309ecc57
Revises: c00b37726656
Create Date: 2026-07-29 21:55:54.168541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision: str = 'c875309ecc57'
down_revision: Union[str, None] = 'c00b37726656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puntos_presion', sa.Column('zona', sa.String(length=50), nullable=True))
    op.add_column('puntos_presion', sa.Column('origen', sa.String(length=100), nullable=True))
    op.add_column('registros_presion', sa.Column('zona', sa.String(length=50), nullable=True))
    op.add_column('registros_presion', sa.Column('origen', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registros_presion', 'origen')
    op.drop_column('registros_presion', 'zona')
    op.drop_column('puntos_presion', 'origen')
    op.drop_column('puntos_presion', 'zona')
    # ### end Alembic commands ###
