"""Add unique constraint to reclamos_historicos

Revision ID: cb239f099008
Revises: 6b22e3062ec5
Create Date: 2026-07-29 23:50:29.843722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision: str = 'cb239f099008'
down_revision: Union[str, None] = '6b22e3062ec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_reclamo_historico', 'reclamos_historicos', ['codigo_solicitud', 'numero_suministro', 'fecha_registro'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_reclamo_historico', 'reclamos_historicos', type_='unique')
    # ### end Alembic commands ###
