"""Sincronizar modelos con BD limpia

Revision ID: e825fc93240e
Revises: d4e5f6a7b8c9
Create Date: 2026-07-05 23:19:40.140813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


revision: str = 'e825fc93240e'
down_revision: Union[str, None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_os_secuencia_fecha', table_name='os_secuencia')
    op.drop_table('os_secuencia')
    op.drop_index('ix_auditoria_accion_entidad', table_name='auditoria_eventos')
    op.drop_index('ix_auditoria_timestamp', table_name='auditoria_eventos')
    op.add_column('ordenes_servicio', sa.Column('trabajo_ejecutado', sa.Text(), nullable=True))
    op.add_column('ordenes_servicio', sa.Column('problemas', sa.Text(), nullable=True))
    op.add_column('ordenes_servicio', sa.Column('soluciones', sa.Text(), nullable=True))
    op.add_column('ordenes_servicio', sa.Column('comentarios_instrucciones', sa.Text(), nullable=True))
    op.add_column('ordenes_servicio', sa.Column('latitud', sa.Float(), nullable=True))
    op.add_column('ordenes_servicio', sa.Column('longitud', sa.Float(), nullable=True))
    op.add_column('ordenes_servicio', sa.Column('fotos_problema_urls', sa.JSON(), nullable=True))
    op.add_column('ordenes_servicio', sa.Column('fotos_solucion_urls', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ordenes_servicio', 'fotos_solucion_urls')
    op.drop_column('ordenes_servicio', 'fotos_problema_urls')
    op.drop_column('ordenes_servicio', 'longitud')
    op.drop_column('ordenes_servicio', 'latitud')
    op.drop_column('ordenes_servicio', 'comentarios_instrucciones')
    op.drop_column('ordenes_servicio', 'soluciones')
    op.drop_column('ordenes_servicio', 'problemas')
    op.drop_column('ordenes_servicio', 'trabajo_ejecutado')
    op.create_index('ix_auditoria_timestamp', 'auditoria_eventos', ['timestamp'], unique=False)
    op.create_index('ix_auditoria_accion_entidad', 'auditoria_eventos', ['accion', 'entidad'], unique=False)
    op.create_table('os_secuencia',
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('contador', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('fecha', name='os_secuencia_pkey')
    )
    op.create_index('ix_os_secuencia_fecha', 'os_secuencia', ['fecha'], unique=False)
    # ### end Alembic commands ###
