"""initial

Revision ID: 672d6f71abc2
Revises: 
Create Date: 2026-06-01 01:57:56.169275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision: str = '672d6f71abc2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sectores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('geometria', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sectores_id'), 'sectores', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dni', sa.String(length=8), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('rol', sa.Enum('GERENTE', 'JEFE_OFICINA', 'ESPECIALISTA', 'TECNICO_CAMPO', name='rol_usuario'), nullable=False),
    sa.Column('cuadrilla_nombre', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('reclamos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nro_reclamo', sa.String(length=50), nullable=False),
    sa.Column('codigo_cliente', sa.String(length=50), nullable=False),
    sa.Column('fecha_reclamo', sa.DateTime(), nullable=False),
    sa.Column('tipo_reclamo', sa.String(length=150), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=False),
    sa.Column('urbanizacion', sa.String(length=150), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('ubicacion', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sector_id'], ['sectores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nro_reclamo')
    )
    op.create_index(op.f('ix_reclamos_id'), 'reclamos', ['id'], unique=False)
    op.create_table('sensores',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('point_id', sa.String(length=50), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('ubicacion', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sector_id'], ['sectores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('point_id')
    )
    op.create_table('lecturas_presion',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sensor_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('presion', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('temperatura', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sensor_id', 'timestamp', name='uq_sensor_timestamp')
    )
    op.create_index(op.f('ix_lecturas_presion_id'), 'lecturas_presion', ['id'], unique=False)
    op.create_table('ordenes_trabajo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.String(length=50), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('asignado_a', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('prioridad', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('tipo_hallazgo_real', sa.String(length=50), nullable=True),
    sa.Column('material_real', sa.String(length=50), nullable=True),
    sa.Column('diametro_real', sa.String(length=20), nullable=True),
    sa.Column('materiales_usados', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('foto_antes_url', sa.String(length=255), nullable=True),
    sa.Column('foto_despues_url', sa.String(length=255), nullable=True),
    sa.Column('ubicacion_reparacion', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('presion_verificacion_mca', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('justificacion_forzado', sa.Text(), nullable=True),
    sa.Column('firma_tecnico_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['asignado_a'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['sectores.id'], ),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordenes_trabajo_id'), 'ordenes_trabajo', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_index(op.f('ix_ordenes_trabajo_id'), table_name='ordenes_trabajo')
    op.drop_index('idx_ordenes_trabajo_ubicacion_reparacion', table_name='ordenes_trabajo', postgresql_using='gist')
    op.drop_table('ordenes_trabajo')
    op.drop_index(op.f('ix_lecturas_presion_id'), table_name='lecturas_presion')
    op.drop_table('lecturas_presion')
    op.drop_index('idx_sensores_ubicacion', table_name='sensores', postgresql_using='gist')
    op.drop_table('sensores')
    op.drop_index(op.f('ix_reclamos_id'), table_name='reclamos')
    op.drop_index('idx_reclamos_ubicacion', table_name='reclamos', postgresql_using='gist')
    op.drop_table('reclamos')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_sectores_id'), table_name='sectores')
    op.drop_index('idx_sectores_geometria', table_name='sectores', postgresql_using='gist')
    op.drop_table('sectores')
    # ### end Alembic commands ###
